### ISSUE TITLE
但主题本身没有使用pjax时，渲染报错

### ISSUE THREAD

**Issue by appotry** [MaxChang3/hexo-markmap#15]
```
06:46:13.479 ERROR {
  err: TypeError: Cannot read properties of undefined (reading 'pjax')
      at getInnerData (/app/node_modules/hexo-markmap/index.js:22:91)
      at Hexo.<anonymous> (/app/node_modules/hexo-markmap/index.js:41:21)
      at Hexo.tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
      at Hexo.<anonymous> (/app/node_modules/bluebird/js/release/method.js:15:34)
      at /app/node_modules/hexo/lib/extend/filter.js:67:52
      at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
      at Object.gotValue (/app/node_modules/bluebird/js/release/reduce.js:166:18)
      at Object.gotAccum (/app/node_modules/bluebird/js/release/reduce.js:155:25)
      at Object.tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromiseCtx (/app/node_modules/bluebird/js/release/promise.js:641:10)
      at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:97:12)
      at _drainQueue (/app/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:102:5)
      at Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:15:14)
      at process.processImmediate (node:internal/timers:471:21)
} Render HTML failed: posts/cf0f47fd/index.html
06:46:13.483 ERROR TypeError: Cannot read properties of undefined (reading 'pjax')
    at getInnerData (/app/node_modules/hexo-markmap/index.js:22:91)
    at Hexo.<anonymous> (/app/node_modules/hexo-markmap/index.js:41:21)
    at Hexo.tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/app/node_modules/bluebird/js/release/method.js:15:34)
    at /app/node_modules/hexo/lib/extend/filter.js:67:52
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/app/node_modules/bluebird/js/release/reduce.js:166:18)
    at Object.gotAccum (/app/node_modules/bluebird/js/release/reduce.js:155:25)
    at Object.tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/app/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/app/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:15:14)
    at process.processImmediate (node:internal/timers:471:21)
```

使用hexo 主题 [matery](https://github.com/blinkfox/hexo-theme-matery)

**Comment by appotry** [comment]
```
# hexo -v 
INFO  Validating config
hexo: 6.2.0
hexo-cli: 4.3.0
os: linux 5.10.60-qnap Debian GNU/Linux 11 (bullseye) 11 (bullseye)
node: 18.0.0
v8: 10.1.124.8-node.13
uv: 1.43.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.18.1
modules: 108
nghttp2: 1.47.0
napi: 8
llhttp: 6.0.4
openssl: 3.0.2+quic
cldr: 41.0
icu: 71.1
tz: 2022a
unicode: 14.0
ngtcp2: 0.1.0-DEV
nghttp3: 0.1.0-DEV
```

**Comment by MaxChang3** [comment]
不好意思， pjax 的配置读取逻辑有问题，我上次合并代码没看仔细

**Comment by MaxChang3** [comment]
已经发布，更新最新版本即可。

**Comment by appotry** [comment]
赞，新版可用
