### ISSUE TITLE
可选链操作符有兼容性问题

### ISSUE THREAD

**Issue by itdocs-icu** [MaxChang3/hexo-markmap#31]
INFO  Validating config
ERROR {
  err: /root/code_file/wiki/itdocs/node_modules/hexo-markmap/index.js:14
      pjaxEnable: config?.hexo_markmap?.pjax || config?.theme_config?.pjax,
                         ^
  
  SyntaxError: Unexpected token '.'
      at new Script (vm.js:88:7)
      at createScript (vm.js:261:10)
      at runInThisContext (vm.js:309:10)
      at /root/code_file/wiki/itdocs/node_modules/hexo/lib/hexo/index.js:303:18
      at tryCatcher (/root/code_file/wiki/itdocs/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/root/code_file/wiki/itdocs/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/root/code_file/wiki/itdocs/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/root/code_file/wiki/itdocs/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/root/code_file/wiki/itdocs/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/root/code_file/wiki/itdocs/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/root/code_file/wiki/itdocs/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/root/code_file/wiki/itdocs/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/root/code_file/wiki/itdocs/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:461:21)
} Plugin load failed: %s hexo-markmap

**Comment by MaxChang3** [comment]
node.js 13 以下版本不支持可选链操作符。

https://github.com/MaxChang3/hexo-markmap/pull/30 已经做相关适配，但是我最近有点忙，目前还未并入。

可以尝试将代码修改为：

```javascript
hexo.extend.filter.register('after_render:html', (content) =>
  afterRender(content, mainTemplate({
    katexEnable: config && config.hexo_markmap && config.hexo_markmap.katex ? true  : false,
    prismEnable: config && config.hexo_markmap && config.hexo_markmap.prism ? true  : false
  },
    config && hexo_markmap && config.hexo_markmap.CDN ? true : false
  ))
)
```

以上逻辑应该没问题，核心就是替换可选链操作符。 不过我未做测试。
